# Generated by Django 4.1.5 on 2023-01-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobile',
            name='Part',
        ),
    ]
